"""add compressed_size to images

Revision ID: 7aabc7464de0
Revises: 8a8dc19b64c0
Create Date: 2026-07-31 18:50:30.107750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aabc7464de0'
down_revision: Union[str, Sequence[str], None] = '8a8dc19b64c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('compressed_size', sa.Integer(), nullable=True))
    op.drop_column('images', 'original_file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('original_file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('images', 'compressed_size')
    # ### end Alembic commands ###
