"""add_ai_metadata_and_storage_limit

Revision ID: 836500a1feab
Revises: 7aabc7464de0
Create Date: 2026-07-31 21:02:12.658895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836500a1feab'
down_revision: Union[str, Sequence[str], None] = '7aabc7464de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('detections', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('colors', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('storage_limit', sa.Integer(), server_default='52428800', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_limit')
    op.drop_column('images', 'colors')
    op.drop_column('images', 'detections')
    # ### end Alembic commands ###
