"""add original_file_size

Revision ID: 8a8dc19b64c0
Revises: cb2803771b84
Create Date: 2026-07-31 18:17:23.491867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8dc19b64c0'
down_revision: Union[str, Sequence[str], None] = 'cb2803771b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('original_file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'original_file_size')
    # ### end Alembic commands ###
